---
- name: make one instance
  local_action:
    module: ec2
    image: "{{ aws_image }}"
    instance_type: "{{ aws_instance_type }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    keypair: "{{ aws_keypair }}"
    count: "{{ aws_quantity }}"
    instance_tags: "{{ aws_instance_tag }}"
    region: "{{ aws_region }}"
    group: "{{ aws_group }}"
    vpc_subnet_id: "{{ aws_vpc_subnet }}"
    wait: true
  register: ec2_info

- debug: var=ec2_info
- debug: var=item
  with_items: ec2_info.instance_ids

- add_host: hostname={{ item.public_ip }} groupname={{ app_name }}_{{ server_env }}
  with_items: ec2_info.instances

- name: wait for instances to listen on port:22
  wait_for:
    state: started
    host: "{{ item.public_dns_name }}"
    port: 22
  with_items: ec2_info.instances
