---
- name: make one instance
  local_action:
    module: ec2
    image: "{{ image }}"
    instance_type: "{{ instance_type }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    keypair: "{{ keypair }}"
    instance_tags: "{{ instance_tag }}"
    region: "{{ region }}"
    group: "{{ group }}"
    wait: true
  register: ec2_info

- debug: var=ec2_info
- debug: var=item
  with_items: ec2_info.instance_ids

- add_host: hostname={{ item.public_ip }} groupname={{ app_name }}_{{ server_env }}
  with_items: ec2_info.instances

- name: wait for instances to listen on port:22
  wait_for:
    state: started
    host: "{{ item.public_dns_name }}"
    port: 22
  with_items: ec2_info.instances