---
- name: make one instance
  local_action:
    module: ec2
    instance_type: "{{ aws.instance_type }}"
    aws_access_key: "{{ aws.access_key }}"
    aws_secret_key: "{{ aws.secret_key }}"
    count: "{{ aws.quantity }}"
    group: "{{ aws.group }}"
    wait: true
  register: ec2_info
  with_items: "{{ aws.provision }}"

- debug: var=ec2_info
- debug: var=item
  with_items: ec2_info.instance_ids

- add_host: hostname={{ item.public_ip }} groupname={{ app_name }}_{{ server_env }}
  with_items: ec2_info.instances

- name: wait for instances to listen on port:22
  wait_for:
    state: started
    host: "{{ item.public_dns_name }}"
    port: 22
  with_items: ec2_info.instances